project:
  type: book

book:
  title: "Recipes"
  author: "Michael V. DePalatis"
  chapters:
    - index.qmd
    - mains.qmd
    # - references.qmd

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
